### ISSUE TITLE
Method not found on `Wallet.address()`

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [PsychicCat/monero-nodejs#10]
Hi, I’m connecting to my monerod cli wallet via
`var Wallet = new moneroWallet('localhost', '18081');`

which seem to work.
But when doing:

`Wallet.address().then(function(a) { console.log(a) });`

I get following error:
```
{
  "code": -32601,
  "message": "Method not found"
}
```

I tried different methods, also `Wallet.balance()`. Give me the same answer..

This is weird, what’s the issue?
Thank you

**Comment by ThibaultJanBeyer** [comment]
Ah! Sorry, I did not run the -rpc wallet. My bad…

**Comment by sneurlax** [comment]
- [ ] add a unit test for this
