### ISSUE TITLE
[question] Why is wallet.height() asynchronous?

### ISSUE THREAD

**Issue by yeeplusplus** [PsychicCat/monero-nodejs#3]
Why is `wallet.height()` asynchronous, but the rest of the API functions are synchronous?

Is the underlying daemon function asynchronous?

**Comment by PsychicCat** [comment]
Whoops, looks like I need to update the documentation there. All of the API functions are asynchronous, they return a promise which needs to be resolved with a `.then()`

For example to use `wallet.height()`:

``` javascript
wallet.height().then(function(response){
// do something with the response object in here
});
```
