### ISSUE TITLE
How to specify rpc-login username/pass

### ISSUE THREAD

**Issue by spectral-sys0p** [PsychicCat/monero-nodejs#9]
It looks like there's not a way to authenticate to the new monero-wallet-rpc, am I just missing it?

**Comment by nyxynyx** [comment]
Having the same problem with `monero-wallet-rpc.exe` from Monero release version: 0.11.1.0 Helium Hydra

    Wallet.balance().then(function(balance) {
        console.log(balance);
    });

returns 

    <html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1>
    </body></html>
    ^

    SyntaxError: Unexpected token < in JSON at position 0

**Comment by PsychicCat** [comment]
The code is in need of some updates for sure. I haven't updated this since before the v10 release. I can get around to it over the weekend. 

In the meantime, you can use the library as is by starting monero-wallet-cli with --disable-rpc-login, to disable the authentication.

**Comment by spectral-sys0p** [comment]
Awesome, thanks for the workaround and the awesome library!

**Comment by ThibaultJanBeyer** [comment]
@PsychicCat have you found time to work on the login part?
Otherwise, I am willing to start working on a way to add credentials and create a PR…
Just don’t want to do unnecessary double work. Let me know.

**Comment by cruisecoders** [comment]
Hi @PsychicCat 
Have you been able to solve the login part issue.
I got the same error

**Comment by Neha3195g** [comment]
Hi @PsychicCat
Have you been able to solve the authentication issue
Please update .
I got the same error to integrate it with my application

**Comment by sneurlax** [comment]
@ThibaultJanBeyer I am also looking to submit a PR... @PsychicCat you have 2 people offering assistance here, direct/assign issues if you want to do it that way (some organization/direction would be welcome,) otherwise we'll just have at it!

**Comment by PsychicCat** [comment]
Sorry for any frustration. I admit I have not had the time to finish this up. So, after taking a look here is where we are.

monero-wallet-rpc uses HTTP digest authentication, which is a bit tedious to do without some dependencies like `request`, I also see there are some other lightweight options I have not tried. `request` seems like it will work well, easy enough to drop in for the HTTP client. I'm trying it out now and get authenticated but having some issues with monero-wallet-rpc not responding. 

There is also some work that had been done in the `dev-v10` branch of this repo by myself and @amiuhle, resolving some problems that exist in this branch involving the floating point conversion among other things. My intention was that eventually `dev-v10` would become the new master branch but I never finished that refactor. However, the `fetch` API client probably will not be so easy to get working with HTTP Digest authentication. (maybe?)

I don't want to hold anyone back that is using this package now so please feel free to submit a PR.

**Comment by ThibaultJanBeyer** [comment]
@sneurlax go for it. I also have not much time at the moment anymore :(

**Comment by sneurlax** [comment]
I've used `request`. Mind assigning me for the sake of reminders/notifications?

**Comment by PsychicCat** [comment]
@sneurlax Sure, it looks like I need to add you as a collaborator in order to assign this issue to you though. Which is fine by me, I sent an invite.

**Comment by johunsang** [comment]
let options = {
        hostname: this.hostname,
        port: this.port,
        path: '/json_rpc',
        method: 'POST',
        headers: headers,
        auth : 'Basic ' + Buffer.from('user' + ':' + 'password').toString('base64'), //add this
    };

**Comment by sanderfoobar** [comment]
@sneurlax Does `request` work?

**Comment by sneurlax** [comment]
Hey, yes it does.  I've been working on monero-integrations/monerophp, but I'll pivot over here today.  Sorry for sleeping on this.

**Comment by sanderfoobar** [comment]
Oh, was just wondering that for my own project. 

FYI: I've noticed that the specific implementation of DIGEST in monero-rpc requires re-usage of the TCP connection, as opposed to what the RFC says (states via the `opaque` header.. afaik), which is why some javascript HTTP client libs do not work. Good to hear `request` does work.

Here is some network traffic to monero-rpc, one with python (using 2 seperate tcp connections) and one with cURL (which re-uses the tcp connection). You'll see that only cURL succeeds.

https://pastebin.com/raw/M0MLnE7r

**Comment by sneurlax** [comment]
This may be relevant, re: how to keep the requests module alive: https://stackoverflow.com/a/33514724

Good note if that's the case, I'll try both ways later.

**Comment by sanderfoobar** [comment]
Following works:

`./monero-wallet-rpc --rpc-bind-port 18082 --wallet-file /foo/bar.keys --rpc-login 'dsc:dsc'`

```
var request = require('request');

request.post('http://127.0.0.1:18082/json_rpc', {
    forever: true,
    json: {"jsonrpc": "2.0", "id": "0", "method": "getaddress"},
    auth: {
        'user': 'dsc',
        'pass': 'dsc',
        'sendImmediately': false
    }
}, function (err, res, body) {
    console.log(body);
});
```
.

**Comment by sneurlax** [comment]
I've tried for an hour or two to get auth working with just the vanilla `http` module used by this package currently, but it isn't working.  See work in https://github.com/sneurlax/monero-nodejs/tree/feature/auth (missing a lot of dead-ends, like sending auth creds as an object, a base64 buffer, a HTTPDigestAuth result, etc. etc.)

I'm going to do as @skftn has done and use the request module, also wrapping the daemon RPC methods and the wallet RPC methods separately.  Stand by

**Comment by sneurlax** [comment]
request-promise-native should be used instead of request-promise, which depends upon bluebird...
 - [ ] do that^
